
# Use kramdown as markdown parser
# http://kramdown.gettalong.org
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

paginate: 4

email: info@styxit.com

name: Styxit blog
description: A weblog about coding, internet, opensource, php, cakephp, pyhon and my project HTPC-Manager. Probably also some other subjects.
url: http://styxit.github.io

disqus:
  shortname: styxitblog